//
// Created by mkizub on 20.09.2026.
//

#include "../pch.h"

#include "Galaxy.h"

#define DEFINE_ENUM_INSTANCE(NAME)                              \
    template<>                                                  \
    js::EnumDecl<NAME> js::EnumDecl<NAME>::instance

DEFINE_ENUM_INSTANCE(JsAllegiance) ("Allegiance",
{
    {1, "Alliance"},
    {2, "Empire"},
    {3, "Federation"},
    {4, "Frontline Solutions"},
    {5, "Guardian"},
    {6, "Independent"},
    {7, "Pilots Federation"},
    {8, "Thargoid"},
});

DEFINE_ENUM_INSTANCE(JsGovernment) ("Government",
{
    {1, "None"},
    {2, "Anarchy"},
    {3, "Communism"},
    {4, "Confederacy"},
    {5, "Cooperative"},
    {6, "Corporate"},
    {7, "Democracy"},
    {8, "Dictatorship"},
    {9, "Engineer"},
    {10, "Feudal"},
    {11, "Megaconstruction"},
    {12, "Patronage"},
    {13, "Prison"},
    {14, "Prison Colony"},
    {15, "Private Ownership"},
    {16, "Theocracy"},
});

DEFINE_ENUM_INSTANCE(JsEconomy) ("Economy",
{
    {1, "None"},
    {2, "Agriculture"},
    {3, "Colony"},
    {4, "Extraction"},
    {5, "High Tech"},
    {6, "Industrial"},
    {7, "Military"},
    {8, "Prison"},
    {9, "Private Enterprise"},
    {10, "Refinery"},
    {11, "Repair"},
    {12, "Rescue"},
    {13, "Service"},
    {14, "Terraforming"},
    {15, "Tourism"},
});

DEFINE_ENUM_INSTANCE(JsSecurity) ("Security",
{
    {1, "Anarchy"},
    {2, "Low"},
    {3, "Medium"},
    {4, "High"},
});

DEFINE_ENUM_INSTANCE(JsFactionState) ("FactionState",
{
    {1, "None"},
    {2, "Blight"},
    {3, "Boom"},
    {4, "Bust"},
    {5, "Civil Liberty"},
    {6, "Civil Unrest"},
    {7, "Civil War"},
    {8, "Drought"},
    {9, "Election"},
    {10, "Expansion"},
    {11, "Famine"},
    {12, "Infrastructure Failure"},
    {13, "Investment"},
    {14, "Lockdown"},
    {15, "Natural Disaster"},
    {16, "Outbreak"},
    {17, "Pirate Attack"},
    {18, "Public Holiday"},
    {19, "Retreat"},
    {20, "Terrorist Attack"},
    {21, "War"},
});

DEFINE_ENUM_INSTANCE(JsPower) ("Power",
{
    {1, "Aisling Duval"},
    {2, "A. Lavigny-Duval"},
    {3, "Archon Delaine"},
    {4, "Denton Patreus"},
    {5, "Edmund Mahon"},
    {6, "Felicia Winters"},
    {7, "Jerome Archer"},
    {8, "Li Yong-Rui"},
    {9, "Nakato Kaine"},
    {10, "Pranav Antal"},
    {11, "Yuri Grom"},
    {12, "Zemina Torval"},
});

DEFINE_ENUM_INSTANCE(JsPowerState) ("PowerState",
{
    {1, "Unoccupied"},
    {2, "Exploited"},
    {3, "Fortified"},
    {4, "Stronghold"},
});

DEFINE_ENUM_INSTANCE(JsThargoidState) ("ThargoidState",
{
    {1, "None"},
    {2, "Thargoid Controlled"},
    {3, "Thargoid Harvest"},
    {4, "Thargoid Probing"},
    {5, "Thargoid Recovery"},
    {6, "Thargoid Stronghold"},
});

#define u(v) std::to_underlying(v)
DEFINE_ENUM_INSTANCE(JsBodyType) ("BodyType",
{
    {u(TypeNav::Star),                  "Star"},
    {u(TypeNav::Planet),                "Planet"},
    {u(TypeNav::Barycenter),            "Barycentre\fBarycenter\fNull"},
    {u(TypeNav::Ring),                  "Ring"},
    {u(TypeNav::AsteroidCluster),       "AsteroidCluster\fAsteroid Cluster"},
});

DEFINE_ENUM_INSTANCE(JsStationType) ("StationType",
{
    // generic
    {u(TypeNav::SpaceThing),            "Space Object"},
    {u(TypeNav::NavBeacon),             "NavBeacon\fNav Beacon"},
    {u(TypeNav::TouristBeacon),         "TouristBeacon\fTourist Beacon"},
    // space stations
    {u(TypeNav::Orbis),                 "Orbis\fOrbis Starport\fStationONeilOrbis\fStationONeilCylinder"},
    {u(TypeNav::Ocellus),               "Ocellus\fStationBernalSphere\fOcellus Starport"},
    {u(TypeNav::Dodec),                 "Dodec\fStationDodec\fDodec Starport"},
    {u(TypeNav::Coriolis),              "Coriolis\fStationCoriolis\fCoriolis Starport"},
    {u(TypeNav::AsteroidBase),          "AsteroidBase\fAsteroid base"},
    {u(TypeNav::SpaceOutpost),          "Outpost\fSpace Outpost\fOutpost Starport"},
    {u(TypeNav::SpaceInstallation),     "Installation\fSpace Installation"},
    {u(TypeNav::SpaceConstrDepot),      "SpaceConstructionDepot\fSpace Construction Depot"},
    // megaships
    {u(TypeNav::Megaship),              "Megaship\fMega ship"},
    {u(TypeNav::StationMegaShip),       "StationMegaShip\fStation Mega ship"},
    {u(TypeNav::FleetCarrier),          "FleetCarrier\fDrake-Class Carrier"},
    {u(TypeNav::SquadronCarrier),       "SquadronCarrier\fSquadron Carrier"},
    {u(TypeNav::StrongholdCarrier),     "SquadronCarrier\fSquadron Carrier"},
    {u(TypeNav::ColonisationShip),      "SystemColonisationShip\fSystem Colonisation Ship"},
    // planetary
    {u(TypeNav::PlanetaryThing),        "Planetary Object"},
    {u(TypeNav::PlanetaryPort),         "PlanetaryPort\fCraterOutpost\fPlanetary Outpost\fCrater Outpost\fPlanetary City\fPlanetary Port\fDockable Planet Station"},
    {u(TypeNav::EngineerPort),          "EngineerPort\fEngineer Port"},
    {u(TypeNav::Settlement),            "Settlement\fOnFootSettlement\fOdyssey Settlement\fSurface Settlement"},
    {u(TypeNav::PlanetaryInstallation), "PlanetaryInstallation\fPlanetary Installation"},
    {u(TypeNav::PlanetaryConstrDepot),  "PlanetaryConstructionDepot\fPlanetary Construction Depot"},
});
#undef u

DEFINE_ENUM_INSTANCE(JsBodySubType) ("BodySubType",
{
    // planets
    {1, "Ammonia world"},
    {2, "Class I gas giant"},
    {3, "Class II gas giant"},
    {4, "Class III gas giant"},
    {5, "Class IV gas giant"},
    {6, "Class V gas giant"},
    {7, "Earth-like world"},
    {8, "Gas giant with ammonia-based life"},
    {9, "Gas giant with water-based life"},
    {10, "Helium gas giant"},
    {11, "Helium-rich gas giant"},
    {12, "High metal content world"},
    {13, "Icy body"},
    {14, "Metal-rich body"},
    {15, "Rocky Ice world"},
    {16, "Rocky body"},
    {17, "Water giant"},
    {18, "Water world"},
    // stars
    {21, "A (Blue-White super giant) Star"},
    {22, "A (Blue-White) Star"},
    {23, "B (Blue-White super giant) Star"},
    {24, "B (Blue-White) Star"},
    {25, "Black Hole"},
    {26, "C Star"},
    {27, "CJ Star"},
    {28, "CN Star"},
    {29, "F (White super giant) Star"},
    {30, "F (White) Star"},
    {31, "G (White-Yellow super giant) Star"},
    {32, "G (White-Yellow) Star"},
    {33, "Herbig Ae/Be Star"},
    {34, "K (Yellow-Orange giant) Star"},
    {35, "K (Yellow-Orange) Star"},
    {36, "L (Brown dwarf) Star"},
    {37, "M (Red dwarf) Star"},
    {38, "M (Red giant) Star"},
    {39, "M (Red super giant) Star"},
    {40, "MS-type Star"},
    {41, "Neutron Star"},
    {42, "O (Blue-White) Star"},
    {43, "S-type Star"},
    {44, "Supermassive Black Hole"},
    {45, "T (Brown dwarf) Star"},
    {46, "T Tauri Star"},
    {47, "White Dwarf (D) Star"},
    {48, "White Dwarf (DA) Star"},
    {49, "White Dwarf (DAB) Star"},
    {50, "White Dwarf (DAV) Star"},
    {51, "White Dwarf (DAZ) Star"},
    {52, "White Dwarf (DB) Star"},
    {53, "White Dwarf (DBV) Star"},
    {54, "White Dwarf (DBZ) Star"},
    {55, "White Dwarf (DC) Star"},
    {56, "White Dwarf (DCV) Star"},
    {57, "White Dwarf (DQ) Star"},
    {58, "Wolf-Rayet C Star"},
    {59, "Wolf-Rayet N Star"},
    {60, "Wolf-Rayet NC Star"},
    {61, "Wolf-Rayet O Star"},
    {62, "Wolf-Rayet Star"},
    {63, "Y (Brown dwarf) Star"},
});

DEFINE_ENUM_INSTANCE(JsVolcanismType) ("VolcanismType",
{
    {1, "Carbon Dioxide Geysers"},
    {2, "Major Carbon Dioxide Geysers"},
    {3, "Major Metallic Magma"},
    {4, "Major Rocky Magma"},
    {5, "Major Silicate Vapour Geysers"},
    {6, "Major Water Geysers"},
    {7, "Major Water Magma"},
    {8, "Metallic Magma"},
    {9, "Minor Ammonia Magma"},
    {10, "Minor Carbon Dioxide Geysers"},
    {11, "Minor Metallic Magma"},
    {12, "Minor Methane Magma"},
    {13, "Minor Nitrogen Magma"},
    {14, "Minor Rocky Magma"},
    {15, "Minor Silicate Vapour Geysers"},
    {16, "Minor Water Geysers"},
    {17, "Minor Water Magma"},
    {18, "No volcanism"},
    {19, "Rocky Magma"},
    {20, "Silicate Vapour Geysers"},
    {21, "Water Geysers"},
    {22, "Water Magma"},
});

DEFINE_ENUM_INSTANCE(JsAtmosphereType) ("AtmosphereType",
{
    {1, "Ammonia"},
    {2, "Ammonia and Oxygen"},
    {3, "Ammonia-rich"},
    {4, "Argon"},
    {5, "Argon-rich"},
    {6, "Carbon dioxide"},
    {7, "Carbon dioxide-rich"},
    {8, "Helium"},
    {9, "Hot Argon"},
    {10, "Hot Argon-rich"},
    {11, "Hot Carbon dioxide"},
    {12, "Hot Carbon dioxide-rich"},
    {13, "Hot Metallic vapour"},
    {14, "Hot Silicate vapour"},
    {15, "Hot Sulphur dioxide"},
    {16, "Hot Water"},
    {17, "Hot Water-rich"},
    {18, "Hot thick Ammonia"},
    {19, "Hot thick Ammonia-rich"},
    {20, "Hot thick Argon"},
    {21, "Hot thick Argon-rich"},
    {22, "Hot thick Carbon dioxide"},
    {23, "Hot thick Carbon dioxide-rich"},
    {24, "Hot thick Metallic vapour"},
    {25, "Hot thick Methane"},
    {26, "Hot thick Methane-rich"},
    {27, "Hot thick Nitrogen"},
    {28, "Hot thick Silicate vapour"},
    {29, "Hot thick Sulphur dioxide"},
    {30, "Hot thick Water"},
    {31, "Hot thick Water-rich"},
    {32, "Hot thin Carbon dioxide"},
    {33, "Hot thin Metallic vapour"},
    {34, "Hot thin Silicate vapour"},
    {35, "Hot thin Sulphur dioxide"},
    {36, "Methane"},
    {37, "Methane-rich"},
    {38, "Neon"},
    {39, "Neon-rich"},
    {40, "Nitrogen"},
    {41, "No atmosphere"},
    {42, "Oxygen"},
    {43, "Suitable for water-based life"},
    {44, "Sulphur dioxide"},
    {45, "Thick Ammonia"},
    {46, "Thick Ammonia and Oxygen"},
    {47, "Thick Ammonia-rich"},
    {48, "Thick Argon"},
    {49, "Thick Argon-rich"},
    {50, "Thick Carbon dioxide"},
    {51, "Thick Carbon dioxide-rich"},
    {52, "Thick Helium"},
    {53, "Thick Methane"},
    {54, "Thick Methane-rich"},
    {55, "Thick Nitrogen"},
    {56, "Thick No atmosphere"},
    {57, "Thick Suitable for water-based life"},
    {58, "Thick Sulphur dioxide"},
    {59, "Thick Water"},
    {60, "Thick Water-rich"},
    {61, "Thin Ammonia"},
    {62, "Thin Ammonia and Oxygen"},
    {63, "Thin Ammonia-rich"},
    {64, "Thin Argon"},
    {65, "Thin Argon-rich"},
    {66, "Thin Carbon dioxide"},
    {67, "Thin Carbon dioxide-rich"},
    {68, "Thin Helium"},
    {69, "Thin Methane"},
    {70, "Thin Methane-rich"},
    {71, "Thin Neon"},
    {72, "Thin Neon-rich"},
    {73, "Thin Nitrogen"},
    {74, "Thin Oxygen"},
    {75, "Thin Sulphur dioxide"},
    {76, "Thin Water"},
    {77, "Thin Water-rich"},
    {78, "Water"},
    {79, "Water-rich"},

    {80, "Iron"},
    {81, "Silicates"},
    {82, "Hydrogen"},
});

DEFINE_ENUM_INSTANCE(JsSolidType) ("SolidType",
{
    {1, "Ice"},
    {2, "Metal"},
    {3, "Rock"},
});

DEFINE_ENUM_INSTANCE(JsTerraformingState) ("TerraformingState",
{
    {1, "Not terraformable"},
    {2, "Terraformable"},
    {3, "Terraforming"},
    {3, "Terraformed"},
});

DEFINE_ENUM_INSTANCE(JsMaterials) ("Materials",
{
    {1, "Antimony"},
    {2, "Arsenic"},
    {3, "Cadmium"},
    {4, "Carbon"},
    {5, "Iron"},
    {6, "Nickel"},
    {7, "Niobium"},
    {8, "Phosphorus"},
    {9, "Sulphur"},
    {10, "Tellurium"},
    {11, "Tungsten"},
    {12, "Vanadium"},
    {13, "Zinc"},
    {14, "Zirconium"},
    {15, "Germanium"},
    {16, "Manganese"},
    {17, "Molybdenum"},
    {18, "Selenium"},
    {19, "Yttrium"},
    {20, "Ruthenium"},
    {21, "Chromium"},
    {22, "Tin"},
    {23, "Mercury"},
    {24, "Technetium"},
    {25, "Polonium"},
});

DEFINE_ENUM_INSTANCE(JsReserveLevel) ("ReserveLevel",
{
    {1, "Depleted\fDepletedResources"},
    {2, "Low\fLowResources"},
    {3, "Common\fCommonResources"},
    {4, "Major\fMajorResources"},
    {5, "Pristine\fPristineResources"},
});

DEFINE_ENUM_INSTANCE(JsTimestamps) ("Timestamps",
{
    {1, "distanceToArrival"},
    {2, "meanAnomaly"},
    {3, "ascendingNode"},
    {4, "controllingPower"},
    {5, "factions"},
    {6, "powerState"},
    {7, "powers"},
});

DEFINE_ENUM_INSTANCE(JsServices) ("Services",
{
    {1, "Flight Controller"},
    {2, "Station Operations"},
    {3, "Dock"},
    {4, "Autodock"},
    {5, "Station Menu"},
    {6, "Contacts"},
    {7, "Refuel"},
    {8, "Market"},
    {9, "Repair"},
    {10, "Workshop"},
    {11, "Missions"},
    {12, "Search and Rescue"},
    {13, "Missions Generated"},
    {14, "Restock"},
    {15, "Social Space"},
    {16, "Black Market"},
    {17, "Interstellar Factors Contact"},
    {18, "Powerplay"},
    {19, "System Colonisation"},
    {20, "Crew Lounge"},
    {21, "Universal Cartographics"},
    {22, "Outfitting"},
    {23, "Livery"},
    {24, "Construction Services"},
    {25, "Shop"},
    {26, "Bartender"},
    {27, "Vista Genomics"},
    {28, "Shipyard"},
    {29, "Pioneer Supplies"},
    {30, "Apex Interstellar"},
    {31, "Tuning"},
    {32, "Fleet Carrier Fuel"},
    {33, "Fleet Carrier Management"},
    {34, "Frontline Solutions"},
    {35, "Refinery Contact"},
    {36, "Redemption Office"},
    {37, "Technology Broker"},
    {38, "Material Trader"},
    {39, "Squadron Bank"},
    {40, "Fleet Carrier Administration"},
    {41, "On Dock Mission"},
    {42, "Fleet Carrier Vendor"},
});

DEFINE_ENUM_INSTANCE(JsStationState) ("StationState",
{
    {1, "Construction"},
    {2, "Damaged"},
    {3, "DamagedHuman"},
    {4, "UnderAttack"},
    {5, "UnderRepairs"},
});

DEFINE_ENUM_INSTANCE(JsCarrierDockingAccess) ("CarrierDockingAccess",
{
    {1, "None"},
    {2, "Friends"},
    {3, "Squadron"},
    {4, "Squadron Friends"},
    {5, "All"},
});

DEFINE_ENUM_INSTANCE(JsSpectralClass) ("SpectralClass",
{
    {1, "A"},
    {2, "A0"},
    {3, "A1"},
    {4, "A2"},
    {5, "A3"},
    {6, "A4"},
    {7, "A5"},
    {8, "A6"},
    {9, "A7"},
    {10,"A8"},
    {11,"A9"},
    {12,"AeBe0"},
    {13,"AeBe1"},
    {14,"AeBe2"},
    {15,"AeBe3"},
    {16,"AeBe4"},
    {17,"AeBe5"},
    {18,"AeBe6"},
    {19,"AeBe7"},
    {20,"AeBe8"},
    {21,"AeBe9"},
    {22,"B"},
    {23,"B0"},
    {24,"B1"},
    {25,"B2"},
    {26,"B3"},
    {27,"B4"},
    {28,"B5"},
    {29,"B6"},
    {30,"B7"},
    {31,"B8"},
    {32,"B9"},
    {33,"C0"},
    {34,"C1"},
    {35,"C2"},
    {36,"C3"},
    {37,"C4"},
    {38,"C5"},
    {39,"C6"},
    {40,"C7"},
    {41,"C8"},
    {42,"C9"},
    {43,"CJ4"},
    {44,"CJ5"},
    {45,"CJ6"},
    {46,"CN4"},
    {47,"CN5"},
    {48,"CN6"},
    {49,"D5"},
    {50,"D6"},
    {51,"D7"},
    {52,"DA0"},
    {53,"DA1"},
    {54,"DA2"},
    {55,"DA3"},
    {56,"DA4"},
    {57,"DA5"},
    {58,"DA6"},
    {59,"DA7"},
    {60,"DA8"},
    {61,"DA9"},
    {62,"DAB0"},
    {63,"DAV0"},
    {64,"DAZ0"},
    {65,"DAZ5"},
    {66,"DAZ6"},
    {67,"DAZ7"},
    {68,"DAZ8"},
    {69,"DAZ9"},
    {70,"DB0"},
    {71,"DBV0"},
    {72,"DBZ0"},
    {73,"DC0"},
    {74,"DC1"},
    {75,"DC5"},
    {76,"DC7"},
    {77,"DC8"},
    {78,"DC9"},
    {79,"DCV0"},
    {80,"DQ1"},
    {81,"DQ4"},
    {82,"DQ5"},
    {83,"DQ6"},
    {84,"DQ7"},
    {85,"DQ8"},
    {86,"DQ9"},
    {87,"F"},
    {88,"F0"},
    {89,"F1"},
    {90,"F2"},
    {91,"F3"},
    {92,"F4"},
    {93,"F5"},
    {94,"F6"},
    {95,"F7"},
    {96,"F8"},
    {97,"F9"},
    {98,"G"},
    {99,"G0"},
    {100,"G1"},
    {101,"G2"},
    {102,"G3"},
    {103,"G4"},
    {104,"G5"},
    {105,"G6"},
    {106,"G7"},
    {107,"G8"},
    {108,"G9"},
    {109,"H0"},
    {110,"H5"},
    {111,"K"},
    {112,"K0"},
    {113,"K1"},
    {114,"K2"},
    {115,"K3"},
    {116,"K4"},
    {117,"K5"},
    {118,"K6"},
    {119,"K7"},
    {120,"K8"},
    {121,"K9"},
    {122,"L"},
    {123,"L0"},
    {124,"L1"},
    {125,"L2"},
    {126,"L3"},
    {127,"L4"},
    {128,"L5"},
    {129,"L6"},
    {130,"L7"},
    {131,"L8"},
    {132,"L9"},
    {133,"M"},
    {134,"M0"},
    {135,"M1"},
    {136,"M2"},
    {137,"M3"},
    {138,"M4"},
    {139,"M5"},
    {140,"M6"},
    {141,"M7"},
    {142,"M8"},
    {143,"M9"},
    {144,"MS0"},
    {145,"MS1"},
    {146,"MS2"},
    {147,"MS3"},
    {148,"MS4"},
    {149,"MS5"},
    {150,"MS6"},
    {151,"N0"},
    {152,"N3"},
    {153,"N5"},
    {154,"O"},
    {155,"O0"},
    {156,"O1"},
    {157,"O2"},
    {158,"O3"},
    {159,"O4"},
    {160,"O5"},
    {161,"O6"},
    {162,"O7"},
    {163,"O8"},
    {164,"O9"},
    {165,"S0"},
    {166,"S1"},
    {167,"S2"},
    {168,"S3"},
    {169,"S4"},
    {170,"S5"},
    {171,"S6"},
    {172,"S7"},
    {173,"T"},
    {174,"T0"},
    {175,"T1"},
    {176,"T2"},
    {177,"T3"},
    {178,"T4"},
    {179,"T5"},
    {180,"T6"},
    {181,"T7"},
    {182,"T8"},
    {183,"T9"},
    {184,"TTS0"},
    {185,"TTS1"},
    {186,"TTS2"},
    {187,"TTS3"},
    {188,"TTS4"},
    {189,"TTS5"},
    {190,"TTS6"},
    {191,"TTS7"},
    {192,"TTS8"},
    {193,"TTS9"},
    {194,"W1"},
    {195,"W2"},
    {196,"W3"},
    {197,"W4"},
    {198,"W5"},
    {199,"W6"},
    {200,"W7"},
    {201,"W8"},
    {202,"W9"},
    {203,"WC0"},
    {204,"WC2"},
    {205,"WC5"},
    {206,"WC6"},
    {207,"WN0"},
    {208,"WN3"},
    {209,"WN5"},
    {210,"WNC0"},
    {211,"WO0"},
    {212,"Y0"},
    {213,"Y1"},
    {214,"Y2"},
    {215,"Y3"},
    {216,"Y4"},
    {217,"Y5"},
    {218,"Y6"},
    {219,"Y9"},
});

DEFINE_ENUM_INSTANCE(JsLuminosity) ("Luminosity",
{
    {1, "I"},
    {2, "II"},
    {3, "III"},
    {4, "IIIa"},
    {5, "IIIab"},
    {6, "IIIb"},
    {7, "IIa"},
    {8, "IIab"},
    {9, "IIb"},
    {10,"IV"},
    {11,"IVa"},
    {12,"IVab"},
    {13,"IVb"},
    {14,"Ia"},
    {15,"Ia0"},
    {16,"Iab"},
    {17,"Ib"},
    {18,"O"},
    {19,"V"},
    {20,"VI"},
    {21,"VII"},
    {22,"Va"},
    {23,"Vab"},
    {24,"Vb"},
    {25,"Vz"},
});

void gal::init_symbols() {
    js::symbol::DefineSymbols({
        // signals genuses
       "$Codex_Ent_Aleoids_Genus_Name;",
       "$Codex_Ent_Bacterial_Genus_Name;",
       "$Codex_Ent_Brancae_Name;",
       "$Codex_Ent_Cactoid_Genus_Name;",
       "$Codex_Ent_Clypeus_Genus_Name;",
       "$Codex_Ent_Conchas_Genus_Name;",
       "$Codex_Ent_Cone_Name;",
       "$Codex_Ent_Electricae_Genus_Name;",
       "$Codex_Ent_Fonticulus_Genus_Name;",
       "$Codex_Ent_Fumerolas_Genus_Name;",
       "$Codex_Ent_Fungoids_Genus_Name;",
       "$Codex_Ent_Ground_Struct_Ice_Name;",
       "$Codex_Ent_Osseus_Genus_Name;",
       "$Codex_Ent_Recepta_Genus_Name;",
       "$Codex_Ent_Shrubs_Genus_Name;",
       "$Codex_Ent_Sphere_Name;",
       "$Codex_Ent_Stratum_Genus_Name;",
       "$Codex_Ent_Tubus_Genus_Name;",
       "$Codex_Ent_Tussocks_Genus_Name;",
       "$Codex_Ent_Tube_Name;",
       "$Codex_Ent_Vents_Name;",

       // ring/belt types
       "Icy",
       "Metal Rich",
       "Metallic",
       "Rocky",

       // ship types
       "Adder",
       "Alliance Challenger",
       "Alliance Chieftain",
       "Alliance Crusader",
       "Anaconda",
       "Asp Explorer",
       "Asp Scout",
       "Beluga Liner",
       "Caspian Explorer",
       "Cobra MkIII",
       "Cobra MkIV",
       "Cobra MkV",
       "Corsair",
       "Diamondback Explorer",
       "Diamondback Scout",
       "Dolphin",
       "Eagle",
       "Federal Assault Ship",
       "Federal Corvette",
       "Federal Dropship",
       "Federal Gunship",
       "Fer-de-Lance",
       "Hauler",
       "Imperial Clipper",
       "Imperial Courier",
       "Imperial Cutter",
       "Imperial Eagle",
       "Keelback",
       "Kestrel Mk II",
       "Krait MkII",
       "Krait Phantom",
       "Lynx Highliner",
       "Mamba",
       "Mandalay",
       "Orca",
       "Panther Clipper MkII",
       "Python",
       "Python MkII",
       "Sidewinder",
       "Type-10 Defender",
       "Type-11 Prospector",
       "Type-6 Transporter",
       "Type-7 Transporter",
       "Type-8 Transporter",
       "Type-9 Heavy",
       "Viper MkIII",
       "Viper MkIV",
       "Vulture",

       // outfitting categories
       "hardpoint",
       "internal",
       "utility",
       "standard",

       // outfitting modules
       "Power Distributor",
       "Fuel Scoop",
       "Sensors",
       "Life Support",
       "Shield Cell Bank",
       "Auto Field-Maintenance Unit",
       "Power Plant",
       "Shield Generator",
       "Thrusters",
       "Frame Shift Drive",
       "Frame Shift Drive (SCO)",
       "Lightweight Alloy",
       "Reinforced Alloy",
       "Refinery",
       "Military Grade Composite",
       "Prospector Limpet Controller",
       "Frame Shift Drive Interdictor",
       "Hatch Breaker Limpet Controller",
       "Fuel Transfer Limpet Controller",
       "Collector Limpet Controller",
       "Repair Limpet Controller",
       "Reactive Surface Composite",
       "Mirrored Surface Composite",
       "Cargo Rack",
       "Beam Laser",
       "Hull Reinforcement Package",
       "Module Reinforcement Package",
       "Pulse Laser",
       "Cannon",
       "Multi-Cannon",
       "Planetary Vehicle Hangar",
       "Burst Laser",
       "Fuel Tank",
       "Fragment Cannon",
       "Bi-Weave Shield Generator",
       "Shield Booster",
       "Sub-Surface Displacement Missile",
       "Mining Laser",
       "Recon Limpet Controller",
       "Seeker Missile Rack",
       "Cargo Scanner",
       "Kill Warrant Scanner",
       "Economy Class Passenger Cabin",
       "Frame Shift Wake Scanner",
       "Missile Rack",
       "Pulse Wave Analyser",
       "Torpedo Pylon",
       "Fighter Hangar",
       "Rail Gun",
       "Business Class Passenger Cabin",
       "Prismatic Shield Generator",
       "Plasma Accelerator",
       "Mine Launcher",
       "Abrasion Blaster",
       "Xeno Multi Limpet Controller",
       "Mk II Economy Class Passenger Cabin",
       "Mk II Cargo Rack",
       "Seismic Charge Launcher",
       "Mining Multi Limpet Controller",
       "First Class Passenger Cabin",
       "Operations Multi Limpet Controller",
       "Rescue Multi Limpet Controller",
       "Decontamination Limpet Controller",
       "Mk II Business Class Passenger Cabin",
       "Detailed Surface Scanner",
       "Chaff Launcher",
       "Heat Sink Launcher",
       "Standard Docking Computer",
       "Supercruise Assist",
       "Research Limpet Controller",
       "Electronic Countermeasure",
       "Advanced Docking Computer",
       "Shock Mine Launcher",
       "Advanced Planetary Approach Suite",
       "AX Multi-Cannon",
       "AX Missile Rack",
       "Meta Alloy Hull Reinforcement",
       "Planetary Approach Suite",
       "Mk II Mining Multi-Limpet Controller",
       "Luxury Class Passenger Cabin",
       "Mk II Plasma Shock Accelerator",
       "Point Defence",
       "Mining Volley Repeater",
       "Enhanced AX Multi-Cannon",
       "Mk II Supercharge Optimised Frame Shift Drive (SCO)",
       "Remote Release Flak Launcher",
       "Mk II Agile Boost Thrusters",
       "Mk II Gravity Optimised Thrusters",
       "Mk II Vessel Hangar",
       "Universal Multi Limpet Controller",
       "Xeno Scanner",
       "Mk II Ablative Lightweight Alloys",
       "Mk II Ablative Reinforced Alloys",
       "Mk II Ablative Military Grade Composite",
       "Mk II Ablative Reactive Surface Composite",
       "Mk II Ablative Mirrored Surface Composite",
       "Shutdown Field Neutraliser",
       "Pack-Hound Missile Rack",
       "Imperial Hammer Rail Gun",
       "Enforcer Cannon",
       "Advanced Plasma Accelerator",
       "Pulse Disruptor Laser",
       "Retributor Beam Laser",
       "Concord Cannon",
       "Rocket Propelled FSD Disruptor",
       "Pacifier Frag-Cannon",
       "Mining Lance",
       "Cytoscrambler Burst Laser",
       "Thargoid Pulse Neutraliser",
       "Enhanced Xeno Scanner",
       "Advanced Multi-Cannon",
       "Shock Cannon",
       "Enzyme Missile Rack",
       "Advanced Missile Rack",
       "Enhanced AX Missile Rack",
       "Corrosion Resistant Cargo Rack",
       "Remote Release Flechette Launcher",
       "Guardian Shield Reinforcement",
       "Experimental Weapon Stabiliser",
       "Guardian Hull Reinforcement",
       "Guardian Module Reinforcement",
       "Guardian Hybrid Power Distributor",
       "Guardian Hybrid Power Plant",
       "Guardian Shard Cannon",
       "Guardian Plasma Charger",
       "Guardian FSD Booster",
       "Caustic Sink Launcher",
       "Pulse Wave Xeno Scanner",
       "Guardian Nanite Torpedo Pylon",
       "Sub-Surface Extraction Missile",
       "Guardian Gauss Cannon",
       "Enhanced Performance Thrusters",
       "Advanced Discovery Scanner",
       "Intermediate Discovery Scanner",
       "Basic Discovery Scanner",

       // commodity categories
       "Chemicals",
       "Consumer Items",
       "Foods",
       "Industrial Materials",
       "Legal Drugs",
       "Machinery",
       "Medicines",
       "Metals",
       "Minerals",
       "Salvage",
       "Slavery",
       "Technology",
       "Textiles",
       "Waste",
       "Weapons",
    });
}
